### ISSUE TITLE
InvalidOperationException ("Model is null") never called

### ISSUE THREAD

**Issue by Liero** [Burgyn/Samples.MinimalApiFilters#1]
https://github.com/Burgyn/Samples.MinimalApiFilters/blob/c1984fff8c6a4aa70ce54980d03a866c12d013a9/ValidationFilter.cs#L16-L19

There's bug in following lines, IMO
```csharp
if (context.Arguments.First(a => a is T) is not T model) //First throws exception T is not found
{
    throw new InvalidOperationException("Model is null"); //this is never called
}
```

Maybe you meant something like this:

```csharp
T model = context.Arguments.OfType<T>().FirstOrDefault() 
   ?? throw new InvalidOperationException("Model is null");
```

**Comment by Burgyn** [comment]
Hi @Liero,

thank you for the notice. Yes, you are right.

Unfortunately I can't use your code because the validated parameter doesn't have to be the first one.

Just change `First` to `FirstOrDefault`.

```csharp
if (context.Arguments.FirstOrDefault(a => a is T) is not T model)
{
    throw new InvalidOperationException("Model is null");
}
```

thanks.

**Comment by Liero** [comment]
I think my code does exactly that. `OfType<T>()` is the same as `Where(a => a is T)`;

```csharp
object[] arr = new object[] { "string", 123 };
int firstNumber = arr.OfType<int>().FirstOrDefault(); //123
```

**Comment by Burgyn** [comment]
Sorry, to busy today and not reading properly. Of course you're right.
